### ISSUE TITLE
Module excercise5 not found in environment bolt

### ISSUE THREAD

**Issue by lakshmi-github** [puppetlabs/tasks-hands-on-lab#18]
When I try to run a task following this link: https://github.com/puppetlabs/tasks-hands-on-lab/tree/master/5-writing-tasks#write-your-first-task-in-bash I get the error in the title. Am I doing something wrong?

The shell script in relative path modules/exercise5/tasks/init.sh exists under my puppetconf directory.

```
lakshmi@50-204-120-225-static ~/puppetconf> bolt task run excercise5 message=ola --nodes 127.0.0.1:32768,127.0.0.1:32769,127.0.0.1:32770 --user root --password root --modules ./modules
Warning: Support for ruby version 2.0.0 is deprecated and will be removed in a future release. See https://docs.puppet.com/puppet/latest/system_requirements.html#ruby for a list of supported ruby versions.
   (at /Library/Ruby/Gems/2.0.0/gems/bolt-0.5.1/vendored/puppet/lib/puppet.rb:134:in `<module:Puppet>')
/Library/Ruby/Gems/2.0.0/gems/bolt-0.5.1/vendored/puppet/lib/puppet/info_service/task_information_service.rb:20:in `task_data': Module excercise5 not found in environment bolt. (Puppet::Module::MissingModule)
```

Thanks,
Lakshmi

**Comment by garethr** [comment]
Hi @lakshmi-github. I think I know what the error is as I've done this a few times too. You have `excercise` spelt incorrectly, it should be `exercise` in the command. Note the extra `c`. Hopefully that gets you up and running.

**Comment by lakshmi-github** [comment]
Ah, thank you Gareth, that was it.

Best,
Lakshmi
