### ISSUE TITLE
Default Ruby on MacOS Sierra does not work with rastasheep/ubuntu-sshd containers

### ISSUE THREAD

**Issue by stefanlasiewski** [puppetlabs/tasks-hands-on-lab#19]
I'm running MacOS Sierra with the default system Ruby 2.0, and the latest stable Docker-for-Mac 17.09.0-ce-mac35.

If I try the Tasks Hands On Lab and follow the Docker instructions, Bolt cannot log into the `rastasheep/ubuntu-sshd` containers due to SSH key issues. 

Since my environment is fairly common, I thought I'd share a bug report since others might run into this problem.

What would be the right way to workaround this issue when using the system ruby? This isn't strictly an issue with your tool, but a workaround would be appreciated.

---

The system ruby is 2.0.0, and bolt installs fine:

```
stefanl@stefanl:~ $ sw_vers |grep ProductVersion
ProductVersion:	10.12.6
stefanl@stefanl:~ $ which ruby
/usr/bin/ruby
stefanl@stefanl:~ $ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
stefanl@stefanl:~ $ sudo gem install bolt
Successfully installed bolt-0.5.1
Parsing documentation for bolt-0.5.1
1 gem installed
stefanl@stefanl:~ $ bolt --version
0.5.1
stefanl@stefanl:~ $
```

SSH can connect to the containers, but the `bolt` CLI cannot connect due to an issue with the ed25519 key.

```
stefanl@stefanl:Bolt-lab $ docker-compose up --scale ssh=3 -d
Creating network "boltlab_default" with the default driver
stefanl@stefanl:Bolt-lab $ docker-compose ps
    Name             Command        State           Ports        
-----------------------------------------------------------------
boltlab_ssh_1   /usr/sbin/sshd -D   Up      0.0.0.0:32770->22/tcp
boltlab_ssh_2   /usr/sbin/sshd -D   Up      0.0.0.0:32769->22/tcp
boltlab_ssh_3   /usr/sbin/sshd -D   Up      0.0.0.0:32768->22/tcp
stefanl@stefanl:Bolt-lab $ ssh root@127.0.0.1 -p 32770 
root@127.0.0.1's password: 
root@60bf17a01eef:~# id
uid=0(root) gid=0(root) groups=0(root)
root@60bf17a01eef:~# exit
logout
Connection to 127.0.0.1 closed.
stefanl@stefanl:Bolt-lab $

stefanl@stefanl:Bolt-lab $ bolt command run uptime --nodes 127.0.0.1:32770
[2017-10-12 11:21:40.191] ERROR -- unsupported key type `ssh-ed25519'
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::LoadError : "Could not find 'rbnacl' (< 5.0, >= 3.2.0) among 88 total gem(s)"
: nil
Ran on 0 node in 0.03 seconds
stefanl@stefanl:Bolt-lab $
```
 
Sadly, the system Ruby is too old to work with net-ssh's requirements, which leads me down a path to RVM or an alternate Ruby: 

```
stefanl@stefanl:Bolt-lab $ sudo gem install rbnacl rbnacl-libsodium bcrypt_pbkdf
Password:
ERROR:  Error installing rbnacl:
	rbnacl requires Ruby version >= 2.2.6.
ERROR:  Error installing rbnacl-libsodium:
	rbnacl requires Ruby version >= 2.2.6.
Building native extensions.  This could take a while...
Successfully installed bcrypt_pbkdf-1.0.0
Parsing documentation for bcrypt_pbkdf-1.0.0
unable to convert "\xCA" from ASCII-8BIT to UTF-8 for lib/bcrypt_pbkdf_ext.bundle, skipping
1 gem installed
stefanl@stefanl:Bolt-lab $ 
```

I've installed RVM as a workaround. That's working for me.

**Comment by ktreese** [comment]
Just a thought...  Would installing the puppet agent on the Mac and setting the path for gem/ruby to /optpuppetlabs/puppet/bin be another viable workaround to the above issue?  That works a-ok on my end, so I thought I'd share.

**Comment by ahpook** [comment]
@stefanlasiewski this looks like a pretty deep mismatch between the age of system ruby on macOS and the requirements of the modern docker ecosystem - since there's a well understood workaround for this category of problem (`brew install rbenv` and so forth) I'm gonna close this. Thanks for the report!
