### ISSUE TITLE
Bolt does NOT support non-PS1 scripts 

### ISSUE THREAD

**Issue by davidalexander83** [puppetlabs/tasks-hands-on-lab#20]
Documentation in README.md suggests that Python scripts can be run on Windows systems - this is inaccurate per https://puppet.com/docs/bolt/0.x/running_bolt_commands.html.

**Comment by MikaelSmith** [comment]
BOLT-295 was released in 0.14.0. See https://puppet.com/docs/bolt/0.x/bolt_configuration_options.html#winrm-transport-configuration-options for how to configure additional extensions.

**Comment by MikaelSmith** [comment]
Fixing this in docs is tracked as [BOLT-347](https://tickets.puppetlabs.com/browse/BOLT-347).

**Comment by MikaelSmith** [comment]
I believe this has been addressed.
