### ISSUE TITLE
macOS download links are incorrect

### ISSUE THREAD

**Issue by slamble** [puppetlabs/tasks-hands-on-lab#47]
Per https://github.com/puppetlabs/tasks-hands-on-lab/tree/master/01-installing-bolt, the download link for macOS 10.12 (at least) is incorrect. It points to bolt-latest.dmg, should be puppet-bolt-latest.dmg.

**Comment by slamble** [comment]
It looks like this issue also applies to the Windows downloads. For Debian/Ubuntu, it appears to be slightly more subtle - the commands will work, but won't install the latest version - the latest puppet-bolt package is version 0.21.2-1, but the latest bolt package is 0.19.1-1. I haven't checked SuSE/Redhat yet, but I suspect they will have similar issues.

If I get time, I'll update my pull request later today to reflect the package name change for all operating systems (it currently only covers the macOS packages).

**Comment by MikaelSmith** [comment]
Ah, we did update the package name to `puppet-bolt` everywhere, but forgot to update the instructions here. Sorry about that! Thanks for the PR!
